
title : Paw Rights - Study
author :
  name : Amanda Muller
  email : amanda.muller@flinders.edu.au

production_url : https://pawrights.com.au

# Build settings
plugins:
  - jekyll-remote-theme

remote_theme: jonaharagon/jekyll-bootstrap-theme

excerpts:
  show: false
  
bootstrap:
  header_pages:
