
title : Paw Rights - Study
author :
  name : Tanami Muller
  email : weitzeug@gmail.com
  github : Tanami

production_url : https://pawrights.com.au


# Build settings
plugins:
  - jekyll-remote-theme

remote_theme: jonaharagon/jekyll-bootstrap-theme
